version: '3'
services:
  web:
    build:
      context: .
    command: ./docker-run.sh
    volumes:
      - .:/myapp:delegated
      - bundle:/bundle
    ports:
      - "3001:3001"
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:9.3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  bundle:
  postgres_data:
